/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FavoriteRouteImport } from './routes/favorite'
import { Route as DashbordIndexRouteImport } from './routes/dashbord/index'
import { Route as DashbordRoutesRouteImport } from './routes/dashbord/routes'
import { Route as DashbordSkillsRouteImport } from './routes/dashbord/skills'
import { Route as SkillsSkillIdRouteImport } from './routes/skills/$skillId'
import { Route as SkillsNewRouteImport } from './routes/skills/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteRoute = FavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashbordIndexRoute = DashbordIndexRouteImport.update({
  id: '/dashbord/',
  path: '/dashbord/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashbordRoutesRoute = DashbordRoutesRouteImport.update({
  id: '/dashbord/routes',
  path: '/dashbord/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashbordSkillsRoute = DashbordSkillsRouteImport.update({
  id: '/dashbord/skills',
  path: '/dashbord/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/favorite': typeof FavoriteRoute
  '/dashbord/routes': typeof DashbordRoutesRoute
  '/dashbord/skills': typeof DashbordSkillsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/dashbord/': typeof DashbordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/favorite': typeof FavoriteRoute
  '/dashbord/routes': typeof DashbordRoutesRoute
  '/dashbord/skills': typeof DashbordSkillsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/dashbord': typeof DashbordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/favorite': typeof FavoriteRoute
  '/dashbord/routes': typeof DashbordRoutesRoute
  '/dashbord/skills': typeof DashbordSkillsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/dashbord/': typeof DashbordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/favorite'
    | '/dashbord/routes'
    | '/dashbord/skills'
    | '/skills/$skillId'
    | '/skills/new'
    | '/dashbord/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/favorite'
    | '/dashbord/routes'
    | '/dashbord/skills'
    | '/skills/$skillId'
    | '/skills/new'
    | '/dashbord'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/favorite'
    | '/dashbord/routes'
    | '/dashbord/skills'
    | '/skills/$skillId'
    | '/skills/new'
    | '/dashbord/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FavoriteRoute: typeof FavoriteRoute
  DashbordRoutesRoute: typeof DashbordRoutesRoute
  DashbordSkillsRoute: typeof DashbordSkillsRoute
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  SkillsNewRoute: typeof SkillsNewRoute
  DashbordIndexRoute: typeof DashbordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite': {
      id: '/favorite'
      path: '/favorite'
      fullPath: '/favorite'
      preLoaderRoute: typeof FavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashbord/': {
      id: '/dashbord/'
      path: '/dashbord'
      fullPath: '/dashbord/'
      preLoaderRoute: typeof DashbordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashbord/routes': {
      id: '/dashbord/routes'
      path: '/dashbord/routes'
      fullPath: '/dashbord/routes'
      preLoaderRoute: typeof DashbordRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashbord/skills': {
      id: '/dashbord/skills'
      path: '/dashbord/skills'
      fullPath: '/dashbord/skills'
      preLoaderRoute: typeof DashbordSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FavoriteRoute: FavoriteRoute,
  DashbordRoutesRoute: DashbordRoutesRoute,
  DashbordSkillsRoute: DashbordSkillsRoute,
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  SkillsNewRoute: SkillsNewRoute,
  DashbordIndexRoute: DashbordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
