/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char38skillsRouteImport } from './routes/&skills'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SkillsNewRouteImport } from './routes/skills/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char38skillsRoute = Char38skillsRouteImport.update({
  id: '/&skills',
  path: '/&skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/&skills': typeof Char38skillsRoute
  '/contact': typeof ContactRoute
  '/skills/new': typeof SkillsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/&skills': typeof Char38skillsRoute
  '/contact': typeof ContactRoute
  '/skills/new': typeof SkillsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/&skills': typeof Char38skillsRoute
  '/contact': typeof ContactRoute
  '/skills/new': typeof SkillsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/&skills' | '/contact' | '/skills/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/&skills' | '/contact' | '/skills/new'
  id: '__root__' | '/' | '/&skills' | '/contact' | '/skills/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char38skillsRoute: typeof Char38skillsRoute
  ContactRoute: typeof ContactRoute
  SkillsNewRoute: typeof SkillsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/&skills': {
      id: '/&skills'
      path: '/&skills'
      fullPath: '/&skills'
      preLoaderRoute: typeof Char38skillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char38skillsRoute: Char38skillsRoute,
  ContactRoute: ContactRoute,
  SkillsNewRoute: SkillsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
